# Generated by Django 4.2.5 on 2026-02-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0058_type_patient_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_api_url', models.URLField()),
                ('local_api_url', models.URLField(blank=True, null=True)),
                ('api_token', models.CharField(max_length=500)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_interval', models.IntegerField(default=300)),
                ('models_to_sync', models.JSONField(default=list)),
                ('last_sync_upload', models.DateTimeField(blank=True, null=True)),
                ('last_sync_download', models.DateTimeField(blank=True, null=True)),
                ('conflict_strategy', models.CharField(choices=[('LOCAL_WINS', 'Local gagne'), ('REMOTE_WINS', 'Remote gagne'), ('MANUAL', 'Résolution manuelle')], default='MANUAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'db_table': 'sync_config',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('UPLOAD', 'Local → Online'), ('DOWNLOAD', 'Online → Local')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CONFLICT', 'Conflit')], default='PENDING', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('operation', models.CharField(max_length=20)),
                ('data_snapshot', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('syncedAt', models.DateTimeField(blank=True, null=True)),
                ('local_updated_at', models.DateTimeField()),
                ('remote_updated_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='sync_log_hospita_3c2d96_idx'), models.Index(fields=['content_type', 'object_id'], name='sync_log_content_4d8cc0_idx'), models.Index(fields=['createdAt'], name='sync_log_created_f45fe0_idx')],
            },
        ),
    ]
