# Generated by Django 4.2.5 on 2026-03-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hospital', '0059_structurearticle_is_shared'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncconfig',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='synclog',
            old_name='local_updated_at',
            new_name='local_updatedAt',
        ),
        migrations.RenameField(
            model_name='synclog',
            old_name='remote_updated_at',
            new_name='remote_updatedAt',
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
