# Generated by Django 4.2.5 on 2026-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cmup',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
