# Generated by Django 4.2.5 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_ingredient_cmup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailssupplies',
            name='arrival_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='business_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='stock_initial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
