# Generated by Django 4.2.5 on 2026-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_detailssupplies_arrival_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailssupplies',
            name='quantity_two',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
