# Generated by Django 4.2.5 on 2026-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_detailssupplies_quantity_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailssupplies',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
