# Generated by Django 4.2.5 on 2026-02-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_supplies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='hospital.dish'),
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipe_ingredient',
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.dish')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.recipes'),
        ),
    ]
