# Generated by Django 4.2.5 on 2026-02-09 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_recipes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('name_language', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compose_ingredient',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.RemoveField(
            model_name='dishpreparation',
            name='dish',
        ),
        migrations.CreateModel(
            name='DetailsComposeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('quantity', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('compose_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compose_ingredients', to='hospital.composeingredient')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.ingredient')),
            ],
            options={
                'db_table': 'deyails_compose_ingredient',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='ComposeIngredientTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('compose_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospital.composeingredient')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compose_ingredient_translation',
                'unique_together': {('compose_ingredient', 'language')},
            },
        ),
    ]
