# Generated by Django 4.2.5 on 2026-02-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_composeingredient_remove_dishpreparation_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsbillsingredient',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='detailsbillsingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.ingredient'),
        ),
    ]
