# Generated by Django 4.2.5 on 2026-02-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_detailsbillsingredient_compose_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composeingredient',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='stock_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.ingredient'),
        ),
    ]
