# Generated by Django 4.2.5 on 2026-02-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_composeingredient_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementstock',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.ingredient'),
        ),
    ]
