# Generated by Django 4.2.5 on 2026-02-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_recipeingredient_compose_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsbillsingredient',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='detailsbillsingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient'),
        ),
        migrations.AlterField(
            model_name='detailscomposeingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient'),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient'),
        ),
    ]
