# Generated by Django 4.2.5 on 2026-02-11 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_detailsbillsingredient_compose_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('stock_quantity', models.FloatField(default=0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('compose_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compose_preparation',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='DetailsComposePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('compose_preparation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composepreparation')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'details_compose_preparation',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='ComposePreparationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('compose_preparation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospital.composepreparation')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compose_preparation_translation',
                'unique_together': {('compose_preparation', 'language')},
            },
        ),
    ]
