# Generated by Django 4.2.5 on 2026-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_composepreparation_detailscomposepreparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailscomposepreparation',
            name='cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
