# Generated by Django 4.2.5 on 2026-02-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_detailscomposepreparation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='compose_ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='compose_preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composepreparation'),
        ),
    ]
