# Generated by Django 4.2.5 on 2026-02-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_remove_detailsbillsingredient_compose_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementstock',
            name='compose_ingredient',
        ),
        migrations.AddField(
            model_name='movementstock',
            name='compose_preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composepreparation'),
        ),
    ]
