# Generated by Django 4.2.5 on 2026-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_remove_movementstock_compose_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCE', 'Divorce'), ('WIDOW', 'Widow')], max_length=255, null=True),
        ),
    ]
