# Generated by Django 4.2.5 on 2026-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_bills_status_alter_patient_maritalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsettlement',
            name='amount_bank_card',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='amount_cash',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='amount_momo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='amount_om',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='amount_prepaid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='bank_card_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='transaction_ref_bank_card',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='transaction_ref_momo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='transaction_ref_om',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
