# Generated by Django 4.2.5 on 2026-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patientsettlement_amount_bank_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsbills',
            options={'ordering': ('id',)},
        ),
    ]
