# Generated by Django 4.2.5 on 2026-02-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_alter_detailsbills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='compose_preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hospital.composepreparation'),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='supplies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='hospital.supplies'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.dish'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='hospital.recipes'),
        ),
    ]
