# Generated by Django 4.2.5 on 2026-02-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_recipeingredient_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='compose_preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compose_preparations', to='hospital.composepreparation'),
        ),
    ]
