# Generated by Django 4.2.5 on 2026-02-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_detailscomposepreparation_compose_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsinventory',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient'),
        ),
        migrations.CreateModel(
            name='Storage_depots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_depot', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('timeAt', models.TimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'db_table': 'storage_depots',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='DetailsStock_movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('stock_initial', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('type_movement', models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('TRANSFER', 'Transfer'), ('EXIT', 'Exit')], max_length=255)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('timeAt', models.TimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('deleted', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient')),
                ('stock_movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.stock_movement')),
                ('storage_depots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots')),
                ('storage_depots_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_depots_dest', to='hospital.storage_depots')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'details_stock_movement',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.AddField(
            model_name='bills',
            name='storage_depots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
    ]
