# Generated by Django 4.2.5 on 2026-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_detailsinventory_ingredient_storage_depots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='overpayment_action',
            field=models.CharField(blank=True, choices=[('PREPAID', 'PREPAID'), ('REFUND', 'REFUND')], max_length=255, null=True),
        ),
    ]
