# Generated by Django 4.2.5 on 2026-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_bills_overpayment_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsettlement',
            name='overpayment_action',
            field=models.CharField(blank=True, choices=[('PREPAID', 'PREPAID'), ('CASH', 'CASH')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='overpayment_action',
            field=models.CharField(blank=True, choices=[('PREPAID', 'PREPAID'), ('CASH', 'CASH')], max_length=255, null=True),
        ),
    ]
