# Generated by Django 4.2.5 on 2026-02-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_patientsettlement_overpayment_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspatientaccount',
            name='reference_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detailspatientaccount',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock_movement',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
        migrations.AddField(
            model_name='stock_movement',
            name='storage_depots_dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='hospital.storage_depots'),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='reference_id',
            field=models.IntegerField(null=True),
        ),
    ]
