# Generated by Django 4.2.5 on 2026-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_detailspatientaccount_reference_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detailspatientaccount',
            index=models.Index(fields=['type_operation', 'hospital', 'source'], name='details_pat_type_op_fd8b67_idx'),
        ),
        migrations.AddIndex(
            model_name='detailspatientaccount',
            index=models.Index(fields=['reference_id'], name='details_pat_referen_0249d2_idx'),
        ),
        migrations.AddIndex(
            model_name='detailspatientaccount',
            index=models.Index(fields=['-createdAt'], name='details_pat_created_b18a22_idx'),
        ),
    ]
