# Generated by Django 4.2.5 on 2026-02-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_detailspatientaccount_details_pat_type_op_fd8b67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsbills',
            name='promotion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.promotion'),
        ),
    ]
