# Generated by Django 4.2.5 on 2026-02-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_detailsbills_promotion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsbills',
            old_name='promotion_id',
            new_name='promotion',
        ),
    ]
