# Generated by Django 4.2.5 on 2026-02-15 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_rename_promotion_id_detailsbills_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_two', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('timeAt', models.TimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('deleted', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.ingredient')),
                ('storage_depots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots')),
            ],
            options={
                'db_table': 'stock',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospital.storage_depots')),
            ],
            options={
                'db_table': 'warehouse_translation',
                'unique_together': {('warehouse', 'language')},
            },
        ),
    ]
