# Generated by Django 4.2.5 on 2026-02-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_stock_warehousetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage_depots',
            name='name',
        ),
        migrations.AddField(
            model_name='storage_depots',
            name='name_language',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
