# Generated by Django 4.2.5 on 2026-02-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_remove_storage_depots_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage_depots',
            old_name='default_depot',
            new_name='is_default',
        ),
        migrations.RemoveField(
            model_name='storage_depots',
            name='name_responsible',
        ),
    ]
