# Generated by Django 4.2.5 on 2026-02-16 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0035_rename_default_depot_storage_depots_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedgroup',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='extendedpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='auth.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='extendedgroup',
            unique_together={('group', 'hospital')},
        ),
        migrations.AlterUniqueTogether(
            name='extendedpermission',
            unique_together={('hospital', 'permission')},
        ),
        migrations.AddIndex(
            model_name='extendedpermission',
            index=models.Index(fields=['hospital', 'is_active'], name='extended_pe_hospita_03ffb1_idx'),
        ),
    ]
