# Generated by Django 4.2.5 on 2026-02-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0036_extendedgroup_createdat_extendedgroup_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_permissions', to='auth.permission'),
        ),
    ]
