# Generated by Django 4.2.5 on 2026-02-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_alter_extendedpermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_movement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detailsstock_movement',
            name='stock_movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='hospital.stock_movement'),
        ),
    ]
