# Generated by Django 4.2.5 on 2026-02-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_stock_movement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_fund',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
