# Generated by Django 4.2.5 on 2026-02-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_alter_cash_cash_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
    ]
