# Generated by Django 4.2.5 on 2026-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_inventory_storage_depots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_quantity_two',
        ),
    ]
