# Generated by Django 4.2.5 on 2026-02-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0041_remove_ingredient_stock_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='composeingredient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='composeingredienttranslation',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='dishpreparation',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='dishtranslation',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='ingredienttranslation',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.dish', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='detailscomposeingredient',
            unique_together={('compose_ingredient', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='detailscomposepreparation',
            unique_together={('compose_preparation', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='detailsinventory',
            unique_together={('inventory', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='detailsstock_movement',
            unique_together={('stock_movement', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='detailssupplies',
            unique_together={('supplies', 'ingredient')},
        ),
        migrations.RemoveField(
            model_name='detailscomposeingredient',
            name='hospital',
        ),
        migrations.CreateModel(
            name='StructureArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('price', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hospital.promotion')),
            ],
            options={
                'db_table': 'structure_article',
                'ordering': ('-id',),
                'unique_together': {('hospital', 'ingredient')},
            },
        ),
    ]
