# Generated by Django 4.2.5 on 2026-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0042_remove_category_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurearticle',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
