# Generated by Django 4.2.5 on 2026-02-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0043_alter_structurearticle_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='structurearticle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='structurearticle',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hospital.dish'),
        ),
        migrations.AlterUniqueTogether(
            name='structurearticle',
            unique_together={('hospital', 'dish')},
        ),
        migrations.RemoveField(
            model_name='structurearticle',
            name='ingredient',
        ),
    ]
