# Generated by Django 4.2.5 on 2026-02-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0044_alter_structurearticle_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_movement',
            name='storage_depots_dest',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='hospital.ingredient'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='hospital.storage_depots'),
        ),
    ]
