# Generated by Django 4.2.5 on 2026-02-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0045_remove_stock_movement_storage_depots_dest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsbills',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
    ]
