# Generated by Django 4.2.5 on 2026-02-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0046_detailsbills_storage_depots'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailscomposepreparation',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composes', to='hospital.composeingredient'),
        ),
    ]
