# Generated by Django 4.2.5 on 2026-02-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0047_detailscomposepreparation_compose_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsinventory',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='hospital.inventory'),
        ),
    ]
