# Generated by Django 4.2.5 on 2026-02-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0049_inventory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsinventory',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
        migrations.AlterField(
            model_name='detailsinventory',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.inventory'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.dish'),
        ),
    ]
