# Generated by Django 4.2.5 on 2026-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0050_detailsinventory_storage_depots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailssupplies',
            name='unit_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
