# Generated by Django 4.2.5 on 2026-02-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0052_remove_recipeingredient_compose_preparation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsbillsingredient',
            name='compose_preparation',
        ),
        migrations.AddField(
            model_name='detailsbillsingredient',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient'),
        ),
    ]
