# Generated by Django 4.2.5 on 2026-02-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_remove_detailsbillsingredient_compose_preparation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('ingredient__isnull', False)), fields=('recipes', 'dish', 'ingredient'), name='unique_recipe_dish_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('compose_ingredient__isnull', False)), fields=('recipes', 'dish', 'compose_ingredient'), name='unique_recipe_dish_compose'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compose_ingredient__isnull', True), ('ingredient__isnull', False)), models.Q(('compose_ingredient__isnull', False), ('ingredient__isnull', True)), _connector='OR'), name='only_one_ingredient_type'),
        ),
    ]
