# Generated by Django 4.2.5 on 2026-02-25 09:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0054_recipeingredient_unique_recipe_dish_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailscomposepreparation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movementstock',
            name='compose_preparation',
        ),
        migrations.AddField(
            model_name='movementstock',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient'),
        ),
        migrations.AddField(
            model_name='stock',
            name='compose_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.composeingredient'),
        ),
        migrations.AlterField(
            model_name='composepreparation',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='quantity_two',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_two',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('ingredient__isnull', False)), fields=('hospital', 'storage_depots', 'ingredient'), name='unique_stock_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('compose_ingredient__isnull', False), ('deleted', False)), fields=('hospital', 'storage_depots', 'compose_ingredient'), name='unique_stock_compose'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compose_ingredient__isnull', True), ('ingredient__isnull', False)), models.Q(('compose_ingredient__isnull', False), ('ingredient__isnull', True)), _connector='OR'), name='only_one_stock_type'),
        ),
    ]
