# Generated by Django 4.2.5 on 2026-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0055_alter_detailscomposepreparation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_type',
            field=models.CharField(choices=[('ONSITE', 'onsite'), ('DELIVERY', 'delivery'), ('CATERING', 'catering'), ('EVENT', 'event')], max_length=255),
        )
    ]
