# Generated by Django 4.2.5 on 2026-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0056_alter_bills_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='expected_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
