# Generated by Django 4.2.5 on 2026-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0057_deliveryinfo_expected_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_patient',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
