# Generated by Django 4.2.5 on 2026-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0058_type_patient_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurearticle',
            name='is_shared',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
